name: ci-latest-release

on:
  push:
    branches: [main]
    paths:
      - "KubeArmor/**"
      - "protobuf/**"
      - ".github/workflows/ci-latest-release.yml"
      - "pkg/**"
      - "!STABLE-RELEASE"
  pull_request:
    branches: [main]
    paths:
      - "KubeArmor/**"
      - "tests/**"
      - "protobuf/**"
      - ".github/workflows/ci-test-ginkgo.yml"
      - "examples/multiubuntu/build/**"
      - "pkg/KubeArmorOperator/**"
      - "deployments/helm/**"

  # create:
  #   branches:
  #     - "v*"

# Declare default permissions as read only.
permissions: read-all

jobs:
  check:
    name: Check what pkg were updated
    if: github.repository == 'Aryan-sharma11/kubearmor'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      kubearmor: ${{ steps.filter.outputs.kubearmor}}
      controller: ${{ steps.filter.outputs.controller }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          kubearmor:
            - "KubeArmor/**"
            - "protobuf/**"
          controller:
            - 'pkg/KubeArmorController/**'

  build:
    name: Create KubeArmor latest release
    needs: check
    if: github.repository == 'Aryan-sharma11/kubearmor'
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
    timeout-minutes: 150
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'KubeArmor/go.mod'
      - name: Install the latest LLVM toolchain
        run: ./.github/workflows/install-llvm.sh

      - name: Compile libbpf
        run: ./.github/workflows/install-libbpf.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: aryan1126
          password: aryan1126

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8

      - name: Push KubeArmor images to Docker
        run: GITHUB_SHA=$GITHUB_SHA ./KubeArmor/build/push_kubearmor.sh ${{ steps.vars.outputs.tag }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@main

      - name: Get Image Digest
        id: digest
        run: |
          echo "imagedigest=$(jq -r '.["containerimage.digest"]' kubearmor.json)" >> $GITHUB_OUTPUT
          echo "initdigest=$(jq -r '.["containerimage.digest"]' kubearmor-init.json)" >> $GITHUB_OUTPUT
          echo "ubidigest=$(jq -r '.["containerimage.digest"]' kubearmor-ubi.json)" >> $GITHUB_OUTPUT

      - name: Sign the Container Images
        run: |
          cosign sign -r kubearmor/kubearmor@${{ steps.digest.outputs.imagedigest }} --yes
          cosign sign -r kubearmor/kubearmor-init@${{ steps.digest.outputs.initdigest }} --yes
          cosign sign -r kubearmor/kubearmor-ubi@${{ steps.digest.outputs.ubidigest }} --yes
  