name: ci-test-go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  issue_comment:
    types:
      - created

jobs:
  go-fmt:
    if: github.event_name == 'push' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/deploy')) || github.event_name == 'pull_request'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: v1.20

      - name: Check gofmt
        run: make gofmt
        working-directory: KubeArmor

  go-lint:
    if: github.event_name == 'push' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/deploy')) || github.event_name == 'pull_request'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: v1.20

      - name: Run Revive Action on KubeArmor
        uses: morphy2k/revive-action@v2
        with:
          path: "./KubeArmor/..."

  go-lint-tests:
    if: github.event_name == 'push' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/deploy')) || github.event_name == 'pull_request'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: v1.20

      - name: Run Revive Action on KubeArmor tests
        uses: morphy2k/revive-action@v2
        with:
          path: "./tests/..."

  go-sec:
    if: github.event_name == 'push' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/deploy')) || github.event_name == 'pull_request'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: v1.20

      - name: Run Gosec Security Scanner
        run: make gosec
        working-directory: KubeArmor

  license:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Check License Header
        uses: apache/skywalking-eyes@9bd5feb86b5817aa6072b008f9866a2c3bbc8587
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
